Spsh 448 autocomplete
dBildungsplattform/schulportal-client pull request #113
Opened 2024-03-19 00:09 UTC by YoussefBouch

# Description

## Links to Tickets or other PRs

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-03-25 15:44 UTC, YoussefBouch commented
Beim Testen auf Autodeployment kommt sowas... Backend Branch ist wirklich main? 
```
{
    "message": "Cannot GET /api/personenkontext/rollen?rolleName=Rol&limit=25",
    "error": "Not Found",
    "statusCode": 404
}
```

2024-03-26 10:14 UTC, jaggarnaut requested changes
1. Der Chrome Autocompleter überlagert das Menü
![image](https://github.com/dBildungsplattform/schulportal-client/assets/141040785/1945cc9b-2cef-4c20-8d0f-5f4ed3560c3a)

2. Wenn ich "ro" suche, findet der Autocompleter Einträge
![image](https://github.com/dBildungsplattform/schulportal-client/assets/141040785/bbd5ce58-b861-407e-a0c5-06c35e9f1b2e)

Wenn ich "rol" suche, auf einmal nicht mehr
![image](https://github.com/dBildungsplattform/schulportal-client/assets/141040785/3ba65707-4ae3-407f-bd68-0921a3f9962d)

2024-03-26 10:52 UTC, YoussefBouch commented
> 1. Der Chrome Autocompleter überlagert das Menü
>    ![image](https://private-user-images.githubusercontent.com/141040785/316818645-1945cc9b-2cef-4c20-8d0f-5f4ed3560c3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTAxNzUsIm5iZiI6MTcxMTQ0OTg3NSwicGF0aCI6Ii8xNDEwNDA3ODUvMzE2ODE4NjQ1LTE5NDVjYzliLTJjZWYtNGMyMC04ZDBmLTVmNGVkMzU2MGMzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMDQ0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDc0ZGNmZGZjNmZkY2ZkOWVjNWNmMTdlYzVmZTJmYjdmZDA5NjNiMTRlYjY3YTExNTEzYjY0OGYzOGRkMTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BGjxQ7YK4XcF4JxnVO0KB3RnFZtmY5o2gnhbjJoQCGQ)
> 2. Wenn ich "ro" suche, findet der Autocompleter Einträge
>    ![image](https://private-user-images.githubusercontent.com/141040785/316818908-bbd5ce58-b861-407e-a0c5-06c35e9f1b2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTAxNzUsIm5iZiI6MTcxMTQ0OTg3NSwicGF0aCI6Ii8xNDEwNDA3ODUvMzE2ODE4OTA4LWJiZDVjZTU4LWI4NjEtNDA3ZS1hMGM1LTA2YzM1ZTlmMWIyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMDQ0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjdlMTY4NWNiYjZiNmU5MDVkYTE1MjYzZGNjYTYzYWI2YjRjZjBjOTlmMWZjNjZlZmNhODAxYTJkNjE2NTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f5_ICjyQQLkSeSNrOkEEIy5pWMZB2IioN0qZ9D8jA8Q)
> 
> Wenn ich "rol" suche, auf einmal nicht mehr (anscheinend der gleiche Fehler, den Youssef schon kommentiert hatte) ![image](https://private-user-images.githubusercontent.com/141040785/316819037-3ba65707-4ae3-407f-bd68-0921a3f9962d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTAxNzUsIm5iZiI6MTcxMTQ0OTg3NSwicGF0aCI6Ii8xNDEwNDA3ODUvMzE2ODE5MDM3LTNiYTY1NzA3LTRhZTMtNDA3Zi1iZDY4LTA5MjFhM2Y5OTYyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMDQ0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Yjg5MTNkNDQ0ODI2OTYyZjIxZjNkYmE4ZjlmODY4ODU0ZDY3NDJjYTg2Mjk4MjM0YzNlYjgyN2Y2ZjFkNjEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rCnnsjIzojf4B9U46duGU06qQYz84GxI7eeup05aLso)

1. Sollten wir den Chrome autocompleter deaktivieren?
 
2. und 3. Sollte jetzt gehen ;) 

Anmerkung: Es gibt scheinbar keine Organisation auf der wir eine Rolle haben...

2024-03-26 11:03 UTC, jaggarnaut commented
> > 1. Der Chrome Autocompleter überlagert das Menü
> >    ![image](https://private-user-images.githubusercontent.com/141040785/316818645-1945cc9b-2cef-4c20-8d0f-5f4ed3560c3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTAxNzUsIm5iZiI6MTcxMTQ0OTg3NSwicGF0aCI6Ii8xNDEwNDA3ODUvMzE2ODE4NjQ1LTE5NDVjYzliLTJjZWYtNGMyMC04ZDBmLTVmNGVkMzU2MGMzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMDQ0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDc0ZGNmZGZjNmZkY2ZkOWVjNWNmMTdlYzVmZTJmYjdmZDA5NjNiMTRlYjY3YTExNTEzYjY0OGYzOGRkMTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BGjxQ7YK4XcF4JxnVO0KB3RnFZtmY5o2gnhbjJoQCGQ)
> > 2. Wenn ich "ro" suche, findet der Autocompleter Einträge
> >    ![image](https://private-user-images.githubusercontent.com/141040785/316818908-bbd5ce58-b861-407e-a0c5-06c35e9f1b2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTAxNzUsIm5iZiI6MTcxMTQ0OTg3NSwicGF0aCI6Ii8xNDEwNDA3ODUvMzE2ODE4OTA4LWJiZDVjZTU4LWI4NjEtNDA3ZS1hMGM1LTA2YzM1ZTlmMWIyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMDQ0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjdlMTY4NWNiYjZiNmU5MDVkYTE1MjYzZGNjYTYzYWI2YjRjZjBjOTlmMWZjNjZlZmNhODAxYTJkNjE2NTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f5_ICjyQQLkSeSNrOkEEIy5pWMZB2IioN0qZ9D8jA8Q)
> > 
> > Wenn ich "rol" suche, auf einmal nicht mehr (anscheinend der gleiche Fehler, den Youssef schon kommentiert hatte) ![image](https://private-user-images.githubusercontent.com/141040785/316819037-3ba65707-4ae3-407f-bd68-0921a3f9962d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTAxNzUsIm5iZiI6MTcxMTQ0OTg3NSwicGF0aCI6Ii8xNDEwNDA3ODUvMzE2ODE5MDM3LTNiYTY1NzA3LTRhZTMtNDA3Zi1iZDY4LTA5MjFhM2Y5OTYyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMDQ0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Yjg5MTNkNDQ0ODI2OTYyZjIxZjNkYmE4ZjlmODY4ODU0ZDY3NDJjYTg2Mjk4MjM0YzNlYjgyN2Y2ZjFkNjEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rCnnsjIzojf4B9U46duGU06qQYz84GxI7eeup05aLso)
> 
> 1. Sollten wir den Chrome autocompleter deaktivieren?
> 2. und 3. Sollte jetzt gehen ;)
> 
> Anmerkung: Es gibt scheinbar keine Organisation auf der wir eine Rolle haben...

Wir sollten den Chrome autocomplete grundsätzlich für alle v-autocomplete inputs deaktivieren. Für alles andere ist es eigentlich ok. Vllt kann man das global per CSS lösen. Ansonsten müssen wir es an jedem v-autocomplete hinzufügen.

2024-03-26 12:50 UTC, jaggarnaut requested changes

2024-03-26 14:09 UTC, YoussefBouch commented on src/views/admin/RolleCreationView.vue
> +        return t(`admin.rolle.mappingFrontBackEnd.systemrechte.${systemrechtKey}`);
Das wird gelöst sobald 443 gemerged ist.

2024-03-26 14:10 UTC, YoussefBouch commented on src/views/admin/RolleCreationView.vue
> +              <h3 class="headline-3">5. {{ $t('admin.rolle.assignSystemrechte') }}</h3>
Das wird gelöst sobald 443 gemerged ist.

2024-03-26 14:10 UTC, YoussefBouch commented on src/views/admin/RolleCreationView.vue
> +            <v-col class="text-body bold text-right"> {{ $t('admin.rolle.systemrechte') }}:</v-col>
Das wird gelöst sobald 443 gemerged ist.

2024-03-26 16:55 UTC, jaggarnaut commented on src/views/admin/RolleCreationView.vue
> +  const [selectedSystemRechte, selectedSystemRechtProps]: [
```suggestion
  const [selectedSystemRechte, selectedSystemRechteProps]: [
```

2024-03-27 08:57 UTC, YoussefBouch commented on src/stores/PersonenKontextStore.spec.ts
> +            updatedAt: '2024-03-24T16:35:32.711Z',
Die mockResponse hatte Ich mir direkt aus dem Swagger-doc genommen aber die Fields hier sind nicht pflicht, sollen die raus deiner Sicht?

2024-03-27 09:03 UTC, jaggarnaut commented on src/stores/PersonenKontextStore.spec.ts
> +            updatedAt: '2024-03-24T16:35:32.711Z',
Sie stören nicht, aber wenn sie nicht gebraucht werden, können sie auch raus

2024-03-27 09:04 UTC, YoussefBouch commented on src/stores/PersonenKontextStore.spec.ts
> +            updatedAt: '2024-03-24T16:35:32.711Z',
Okay scheinbar sind die doch Pflicht :D

2024-03-27 09:26 UTC, jaggarnaut approved these changes

2024-03-27 09:34 UTC, YoussefBouch commented
**Bitte nicht mergen.**  Backmerge von main nach Merge von SPSH-443 nötig. (Ein paar Konflikte erwartet).

2024-03-28 13:36 UTC, merged