Spsh 487 angebote for rolle
dBildungsplattform/schulportal-client pull request #126
Opened 2024-04-03 13:52 UTC by jaggarnaut

# Description

## Links to Tickets or other PRs

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-04-15 15:06 UTC, YoussefBouch requested changes

2024-04-15 15:06 UTC, YoussefBouch commented on src/locales/de-DE.json
> +      "assignedServiceProvider": "zugeordnete Angebote",
` "assignedServiceProvider": "Zugeordnete Angebote",`

2024-04-15 15:06 UTC, YoussefBouch commented on src/styles/components/result-table.scss
> +      max-width: 241px;
Damit haben wir Ellipsis für alle Spalten oder? Ist das gewollt?

2024-04-16 08:59 UTC, jaggarnaut commented on src/styles/main.scss
> -.ellipsis-wrapper {
Hab die Nutzung entfernt, das passiert jetzt automatisch für table cells

2024-04-16 09:00 UTC, jaggarnaut commented on src/styles/components/result-table.scss
> +      max-width: 241px;
Finde ich wartbarer als jede Spalte einzeln mit Templates zu bestücken. Soll ich das noch mal mit Christian besprechen?

2024-04-16 09:00 UTC, jaggarnaut commented on src/locales/de-DE.json
> +      "assignedServiceProvider": "zugeordnete Angebote",
done

2024-04-16 10:52 UTC, YoussefBouch commented on src/styles/components/result-table.scss
> +      max-width: 241px;
Finde Ich auch wartbarer, wenn das für fast alles, was lang ist gemacht werden soll... Aber vielleicht einfach Christian Bescheid sagen, dass das jetzt so ist?

2024-04-16 10:53 UTC, YoussefBouch approved these changes

2024-04-16 11:21 UTC, jaggarnaut commented on src/styles/components/result-table.scss
> +      max-width: 241px;
Christian weiß Bescheid, es wird auch noch ein Folgeticket geben, um die Inhalte per Tooltip beim Hover komplett anzuzeigen

2024-04-23 06:47 UTC, merged