Spsh 134 reset password
dBildungsplattform/schulportal-client pull request #15
Opened 2023-11-03 15:24 UTC by jaggarnaut

# Description

## Links to Tickets or other PRs

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-11-17 15:34 UTC, pkleybolte requested changes

2023-11-17 15:34 UTC, pkleybolte commented on src/components/admin/PasswordReset.vue
> +        console.log(error)
Sollten wir dem Nutzer einen Fehler anzeigen?

2023-11-17 15:34 UTC, pkleybolte commented on src/router/routes.ts
> +      requiresAuth: false
Ich denke, dafür muss man eingeloggt sein

2023-11-17 15:34 UTC, pkleybolte commented on src/views/admin/UserManagementView.vue
> +  let itemsPerPage = ref(25)
Wir derzeit nie gelesen. Vorbereitung für Pagination?

2023-11-17 15:34 UTC, pkleybolte commented on src/specs/unit/components/reset-password.spec.ts
> +
describe fehlt

2023-11-17 15:34 UTC, pkleybolte commented on src/specs/unit/components/reset-password.spec.ts
> +test.skip('it shows and hides password', async () => {
Skip muss vor Merge entfernt oder begründet sein.

2023-11-17 15:34 UTC, pkleybolte commented on src/specs/unit/components/user-table.spec.ts
> +
describe fehlt

2023-11-17 15:34 UTC, pkleybolte commented on src/specs/unit/components/cards/provider-card.spec.ts
> +
describe fehlt

2023-11-21 07:31 UTC, jaggarnaut commented on src/specs/unit/components/reset-password.spec.ts
> +test.skip('it shows and hides password', async () => {
Als Begründung ist der Kommentarblock Z.42-47 gedacht. Falls das nicht ausreicht, würde ich die Tests wieder löschen, da wir nach der Config die Tests eh noch einmal überarbeiten wollen.

2023-11-21 08:35 UTC, jaggarnaut commented on src/views/admin/UserManagementView.vue
> +  let itemsPerPage = ref(25)
Entfernt, Pagination kommt später

2023-11-21 12:22 UTC, jaggarnaut commented on src/components/admin/PasswordReset.vue
> +        console.log(error)
Hinzugefügt, aber lokal kann ich es gerade nicht testen.

2023-11-22 16:22 UTC, pkleybolte approved these changes

2023-11-23 07:39 UTC, merged