Added Klassenauswahl to benutzeranlage
dBildungsplattform/schulportal-client pull request #156
Opened 2024-05-07 07:45 UTC by YoussefBouch

# Description

## Links to Tickets or other PRs

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-05-14 11:29 UTC, jaggarnaut requested changes

2024-05-14 11:29 UTC, jaggarnaut commented on src/views/admin/PersonCreationView.vue
> +      }[]
Wollen wir dafür einen Type definieren? Macht auch isLernRolle() etwas kompakter

2024-05-14 13:22 UTC, YoussefBouch commented on src/views/admin/PersonCreationView.vue
> +          <template v-if="selectedRolle && isLernRolle(selectedRolle) && selectedOrganisation">
Geht! :)

2024-05-14 13:23 UTC, YoussefBouch commented on src/views/admin/PersonCreationView.vue
> +            <FormRow
Habe Ich geändert

2024-05-14 13:26 UTC, YoussefBouch commented on src/views/admin/PersonCreationView.vue
> +      }[]
Done.

2024-05-16 11:53 UTC, jaggarnaut requested changes

2024-05-16 17:23 UTC, YoussefBouch commented on src/stores/PersonenkontextStore.ts
> +        this.createdPersonenkontextForOrganisation = data;
Finde Ich eine sehr gute Idee. Done :)

2024-05-17 13:13 UTC, jaggarnaut requested changes

2024-05-17 13:13 UTC, jaggarnaut commented on src/views/admin/PersonCreationView.vue
> +        .createPersonenkontext(unpersistedOrganisationPersonenkontext, OrganisationsTyp.Schule)
Ich würde vorschlagen, dass wir den Typ von selectedOrganisation abfragen, weil Benutzer auch für den Typ Land oder Träger angelegt werden können

2024-05-17 13:57 UTC, YoussefBouch commented on src/views/admin/PersonCreationView.vue
> +        .createPersonenkontext(unpersistedOrganisationPersonenkontext, OrganisationsTyp.Schule)
Da wir nur zwischen Klasse und allen anderen Orgas unterscheiden müssen, habe ich eine Enum erstellt, die das erledigt und abhängig vom angegebenen Parameter den Kontext festlegt. 

Den Typ vom selectedOrganisation geht leider nicht, weil das nur die Id beinhaltet (Kann man ändern, wenn nötig) aber das bringt zur Zeit nicht viel. Ziel ist es nur zu wissen, ob Klasse oder was anders.

2024-05-17 14:09 UTC, jaggarnaut approved these changes

2024-05-21 12:02 UTC, merged