SPSH-615-tooltip-ellipsis
dBildungsplattform/schulportal-client pull request #159
Opened 2024-05-14 10:36 UTC by YoussefBouch

# Description

## Links to Tickets or other PRs
https://ticketsystem.dbildungscloud.de/browse/SPSH-615

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-05-14 11:41 UTC, jaggarnaut requested changes

2024-05-14 11:41 UTC, jaggarnaut commented on src/views/admin/RolleManagementView.vue
> +            :title="item.serviceProviders.join(', ')"
Das zeigt aktuell nur [ object Object ] an

2024-05-14 13:26 UTC, YoussefBouch commented on src/views/admin/RolleManagementView.vue
> +            :title="item.serviceProviders.join(', ')"
Fixed.

2024-05-14 14:24 UTC, jaggarnaut approved these changes

2024-05-15 07:06 UTC, jaggarnaut requested changes

2024-05-15 07:06 UTC, jaggarnaut commented on src/views/admin/PersonManagementView.vue
> +            {{ item.rollen }}
Bei den Rollen sind die '---' verschwunden. Bitte wieder ergänzen.

2024-05-15 08:04 UTC, YoussefBouch commented on src/views/admin/PersonManagementView.vue
> +            {{ item.rollen }}
Done aber wir hatten das auch noch nie da eigentlich.

2024-05-16 07:48 UTC, merged