Spsh 666 benutzer loeschen
dBildungsplattform/schulportal-client pull request #165
Opened 2024-05-21 12:23 UTC by YoussefBouch

# Description

## Links to Tickets or other PRs
https://ticketsystem.dbildungscloud.de/browse/SPSH-666

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-05-22 08:37 UTC, jaggarnaut requested changes

2024-05-22 08:41 UTC, YoussefBouch commented on src/views/admin/PersonDetailsView.vue
Ist schon eingebaut, musste Ich nur noch pushen. ;)

2024-05-22 10:43 UTC, jaggarnaut requested changes

2024-05-22 10:43 UTC, jaggarnaut commented on src/stores/AuthStore.ts
> +  hasPersonenloeschenPermission: boolean;
```suggestion
  hasPersonenLoeschenPermission: boolean;
```

2024-05-22 10:43 UTC, jaggarnaut commented on src/views/admin/PersonDetailsView.vue
> +          <!-- Delete person -->
Wirkt fehl am Platz der Kommentar.

2024-05-22 11:45 UTC, YoussefBouch commented on src/components/admin/PersonDelete.spec.ts
> +// import { VDialog } from 'vuetify/lib/components/index.mjs'
Kann erstmal weg,

2024-05-22 12:41 UTC, jaggarnaut requested changes

2024-05-22 12:41 UTC, jaggarnaut commented on src/components/admin/PersonDelete.vue
> +    message += `\n\n${t('admin.person.deletePersonConfirmation', {
Brauchen wir die new lines \n\n?

2024-05-22 12:41 UTC, jaggarnaut commented on src/components/admin/PersonDelete.vue
> +    message += `\n\n${t('admin.person.deletePersonSuccessMessage', {
Brauchen wir die new lines? \n\n

2024-05-22 13:39 UTC, YoussefBouch commented on src/components/admin/PersonDelete.vue
> +    message += `\n\n${t('admin.person.deletePersonConfirmation', {
Nop, irrelevant

2024-05-23 05:39 UTC, jaggarnaut approved these changes

2024-05-28 09:02 UTC, merged