Spsh 698
dBildungsplattform/schulportal-client pull request #176
Opened 2024-06-15 00:15 UTC by YoussefBouch

# Description

## Links to Tickets or other PRs

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-06-26 15:12 UTC, pkleybolte requested changes

2024-06-26 18:58 UTC, YoussefBouch commented on src/views/admin/PersonDetailsView.vue
> +    isZuordnungFormActive.value = true;
Wenn `isZuordnungFormActive.value = true;` dann sieht man die Form um einen Kontext anzugelen und die Daten in den autocompletes hängen von  `personenkontextStore.processWorkflowStep();`, deswegen sehe Ich das als wichtig hier oder?

2024-06-26 19:36 UTC, YoussefBouch commented on src/composables/useKlassen.ts
> +      .slice(0, 25)
Du hast hier Recht, die API bietet den Parameter "limit" schon und deswegen ist `.slice` überflüssig und erstellt ein extra copy vom Array. 

Die Sortierung ist zur Zeit aber nicht im BE eingebaut bei den Endpunkten und Ich würde das ungern noch im Rahmen von 698 bei mehreren Endpunkten einbauen (Ein extra ticket dafür wäre cool). 

Aussderm erstellt .sort keine Copy und bearbeitet nur das originale Array also nicht so schlimm hier.

2024-06-26 19:38 UTC, YoussefBouch commented on src/components/form/FormWrapper.vue
> +    canCommit: boolean;
Stimmt.

2024-06-26 19:39 UTC, YoussefBouch commented on src/views/admin/PersonDetailsView.vue
>      const updateParams: DbiamUpdatePersonenkontexteBodyParams = {
Hast Recht.

2024-06-26 23:29 UTC, YoussefBouch commented on src/composables/useOrganisationWatcher.ts
> +  watch(selectedOrganisation, (newValue: string, oldValue: string) => {
Ja, machen wir auch an manchen Stellen aber der gibt dir leider nur das "newValue". Man kann hier den oldValue manuell storen aber find Ich nicht so straight forward wie bei den Watchers.

2024-06-27 07:53 UTC, YoussefBouch commented on src/components/form/FormWrapper.vue
> +          :disabled="!canCommit"
Ich werde ein tooltip hinzufügen "Die Rolle passt nicht zur Organisationsebene" on hover auf dem Button.

2024-06-27 08:46 UTC, YoussefBouch commented on src/composables/useKlassen.ts
> +      .slice(0, 25)
Die API bietet hier den Param nicht an.

2024-06-27 08:47 UTC, YoussefBouch commented on src/composables/useOrganisationen.ts
> +      .slice(0, 25)
Slice entfernt und parameter im Request benutzt.

2024-06-27 08:47 UTC, YoussefBouch commented on src/composables/useOrganisationen.ts
> +      .sort((a: TranslatedObject, b: TranslatedObject) => a.title.localeCompare(b.title));
Done.

2024-06-27 08:48 UTC, YoussefBouch commented on src/composables/useRollen.ts
> +      .slice(0, 25)
Done.

2024-06-27 13:33 UTC, YoussefBouch commented on src/views/admin/PersonDetailsView.vue
> +          <template v-if="isZuordnungFormActive && !pendingDeletion">
Guter Vorschlag. Ich habe eine neue Komponente hinzugefügt, die benutzt wird um einen Kontext zu erstellen. Wir nutzen das jetzt auch bei PersonCreationView und die Composables für die Watchers sind nicht mehr nötig.

2024-06-28 06:56 UTC, pkleybolte approved these changes

2024-06-28 06:56 UTC, pkleybolte commented on src/views/admin/PersonCreationView.spec.ts
>      expect(wrapper?.getComponent({ name: 'FormRow' })).toBeTruthy();
`PersonenkontextCreate` ?

2024-07-10 12:36 UTC, merged