SPSH-838
dBildungsplattform/schulportal-client pull request #190
Opened 2024-07-11 12:15 UTC by DeFi3298

2024-07-11 16:18 UTC, YoussefBouch requested changes

2024-07-11 16:18 UTC, YoussefBouch commented on src/components/admin/personen/TwoFactorAuthenticationSetUp.vue
> +                data-testid="close-password-reset-dialog-button"
```suggestion
                data-testid="close-two-way-authentification-dialog-button"
```

2024-07-11 16:18 UTC, YoussefBouch commented on src/components/admin/personen/TwoFactorAuthenticationSetUp.vue
> +                <p v-if="selectedOption === 'software'"> {{ $t('admin.person.twoFactorAuthentication.softwareTokenText') }}</p>
```suggestion
                <p class="text-body" v-if="selectedOption === 'software'"> {{ $t('admin.person.twoFactorAuthentication.softwareTokenText') }}</p>
```

2024-07-11 16:18 UTC, YoussefBouch commented on src/components/admin/personen/TwoFactorAuthenticationSetUp.vue
> +                <p v-if="selectedOption === 'hardware'"> {{ $t('admin.person.twoFactorAuthentication.hardwareTokenText') }}</p>
```suggestion
                <p class="text-body" v-if="selectedOption === 'hardware'"> {{ $t('admin.person.twoFactorAuthentication.hardwareTokenText') }}</p>
```

2024-07-11 16:23 UTC, YoussefBouch requested changes

2024-07-11 16:23 UTC, YoussefBouch commented on src/components/admin/personen/TwoFactorAuthenticationSetUp.vue
> +  const selectedOption = ref('software')
```suggestion
  const selectedOption: Ref<'software' | 'hardware'> = ref('software');
```

2024-07-12 08:57 UTC, DeFi3298 commented on src/components/admin/personen/TwoFactorAuthenticationSetUp.vue
> +                data-testid="close-password-reset-dialog-button"
done

2024-07-12 08:57 UTC, DeFi3298 commented on src/components/admin/personen/TwoFactorAuthenticationSetUp.vue
> +                <p v-if="selectedOption === 'software'"> {{ $t('admin.person.twoFactorAuthentication.softwareTokenText') }}</p>
done

2024-07-12 08:57 UTC, DeFi3298 commented on src/components/admin/personen/TwoFactorAuthenticationSetUp.vue
> +                <p v-if="selectedOption === 'hardware'"> {{ $t('admin.person.twoFactorAuthentication.hardwareTokenText') }}</p>
done

2024-07-12 08:57 UTC, DeFi3298 commented on src/components/admin/personen/TwoFactorAuthenticationSetUp.vue
> +  const selectedOption = ref('software')
done

2024-07-12 10:47 UTC, YoussefBouch approved these changes

2024-07-15 08:05 UTC, merged