Spsh 692 - pagination for result tables
dBildungsplattform/schulportal-client pull request #199
Opened 2024-07-25 13:28 UTC by jaggarnaut

## Links to Tickets or other PRs
https://ticketsystem.dbildungscloud.de/browse/SPSH-692
depends on: https://ticketsystem.dbildungscloud.de/browse/SPSH-922

## To Do
- [ ] pagination for personen
- [ ] pagination for schulen
- [ ] pagination for klassen
- [ ] pagination for rollen
- [ ] design

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-08-07 20:14 UTC, YoussefBouch requested changes
Ich sehe keine Dienstellennummer mehr für die Klassen, liegt vielleicht

2024-08-07 20:14 UTC, YoussefBouch commented on src/views/admin/KlassenManagementView.vue
> -  }
Das muss drin bleiben. Es wird zum finalKlassen Objekt hinzugefügt als extra property um jede Klasse mit ihrem Parent zu matchen beim Mounten.

2024-08-07 20:14 UTC, YoussefBouch commented on src/views/admin/KlassenManagementView.vue
> +  }
Die Dienstellennummer wird jetzt nicht mehr angezeigt. 

**Lösung:**
Hier wird die schuleMap benutzt um den Parent von der Klasse zu finden. Wir nutzen jetzt allSchulen statt allOrganisationen scheinbar und deswegen muss auch bei der Methode fetchSchuleMap das geändert werden.

2024-08-07 20:19 UTC, YoussefBouch reviewed
State management bei Pagination gehört auch zum Ticket oder? Christian damals hatte drauf hingewiesen glaube Ich. Nach Navigierung zu Gesamtübersicht und wieder zurück sollte die Paginierungseinstellung behalten. Wie siehst du das?

2024-08-13 09:14 UTC, jaggarnaut commented
> State management bei Pagination gehört auch zum Ticket oder? Christian damals hatte drauf hingewiesen glaube Ich. Nach Navigierung zu Gesamtübersicht und wieder zurück sollte die Paginierungseinstellung behalten. Wie siehst du das?

Done

2024-08-13 14:38 UTC, YoussefBouch commented
Anmerkungen:

- Wenn Ich auf Page 2 bin z.B. bei Klassenmanagement und dann irgendeine Schule im Filter auswähle dann funktioniert der Filter nicht und zeigt stattdessen alles. 
- 
- Sollten wir in der Lage sein die Paginierte Liste zu filtern? Ich würde sagen das macht Sinn oder? In diesem Fall sollten wir den Filter parallel mit Paginierung aktualisieren damit er die richtigen Schulen zeigt?

2024-08-14 07:47 UTC, jaggarnaut commented
> **Anmerkungen:**
> 
> * Wenn Ich auf Page 2 bin z.B. bei **Klassenmanagement** und dann irgendeine Schule im Filter auswähle dann funktioniert der Filter nicht und zeigt stattdessen alles.
> * Sollten wir in der Lage sein die Paginierte Liste zu filtern? Ich würde sagen das macht Sinn oder? In diesem Fall sollten wir den Filter parallel mit Paginierung aktualisieren damit er die richtigen Schulen zeigt?

Done. Das Problem war, dass bei update der page in der Tabelle noch mal alle neu geladen wurden. Das habe ich jetzt verhindert. Momentan gibt es die Filterung nur bei Personen und Klassen und da funktioniert es jetzt fast immer. Bei Klassen kann man den getKlasseByOrganisationId noch nicht filtern, das kommt mit dem nächsten PR. Bitte teste noch mal.

2024-08-14 11:28 UTC, YoussefBouch commented
**Anmerkung:** 

Wenn Ich jetzt z.B. 35 Carl-Orff-Schulen habe und im Filter die Schule "Carl-Orff-Schule" auswähle dann wird die Liste nicht paginiert und alles wird angezeigt auf einer Seite.

2024-08-14 12:28 UTC, YoussefBouch approved these changes

2024-08-15 08:53 UTC, merged