Spsh 841
dBildungsplattform/schulportal-client pull request #221
Opened 2024-08-27 10:00 UTC by AlexanderUngefug

2024-08-27 13:50 UTC, jaggarnaut requested changes

2024-08-27 13:50 UTC, jaggarnaut commented on src/views/admin/PersonDetailsView.vue
> +                    :disabled="isEditActive"
Wieso hat dieser Button kein Tooltip mehr?

2024-08-28 07:23 UTC, AlexanderUngefug commented on src/views/admin/PersonDetailsView.vue
> +                    :disabled="isEditActive"
da ist was beim Mergen schief gelaufen. Ist korrigiert

2024-08-28 08:21 UTC, jaggarnaut requested changes

2024-08-28 08:21 UTC, jaggarnaut commented on src/components/two-factor-authentication/HardwareTokenWorkflow.vue
> +          data-testid="hardwareToken-input"
```suggestion
          data-testid="hardware-token-input"
```
ids und refs der inputs haben teilweise noch andere schreibweise, bitte alle felder prüfen.

2024-08-28 08:21 UTC, jaggarnaut commented on src/locales/de-DE.json
> +          "UNKOWN_ERROR": "Ein unbekannter Fehler ist aufgetreten."
```suggestion
          "UNKNOWN_ERROR": "Ein unbekannter Fehler ist aufgetreten."
```

2024-08-29 06:54 UTC, jaggarnaut approved these changes

2024-09-05 13:16 UTC, merged