Spsh 812
dBildungsplattform/schulportal-client pull request #223
Opened 2024-08-27 15:25 UTC by jaggarnaut

## Links to Tickets or other PRs
https://ticketsystem.dbildungscloud.de/browse/SPSH-812

depends on:
https://github.com/dBildungsplattform/schulportal-client/pull/218
https://github.com/dBildungsplattform/dbildungs-iam-server/pull/626

2024-09-04 19:12 UTC, YoussefBouch approved these changes

2024-09-04 20:20 UTC, YoussefBouch requested changes

2024-09-04 20:20 UTC, YoussefBouch commented on src/views/admin/PersonDetailsView.vue
> +                  v-if="!hasKopersRolle && isKopersRolle(selectedRolle) && selectedOrganisation"
`HasKopersRolle ` : Das wird bei SPSH-811 benutzt um die vorhandenen Kontexte auszuwerten. Wenn mindestens 1 Rolle Koperspflicht ist dann zeigen wir den Text "Fehlt" in Rot. 

Wenn wir aber das hier so nutzen heisst das: KopersNr Inputfield wird nie gezeigt im Falle, wenn wir eine Person mit einer bestehenden Rolle, dass Koperspflichtig ist... Das heisst dann auch: Ich kann die KopersNr gar nicht nachreichen. 

Ich würde das hier also entfernen.

2024-09-04 20:20 UTC, YoussefBouch commented on src/views/admin/PersonDetailsView.vue
> +                ></KopersInput>
Eine zweite Anmerkung: Wir sollten den inputfield für KopersNr nur anbieten, wenn der Person-Endpunkt eine fehlende KopersNr zurückgibt sonst überschreiben wir die vorhandene Personalnummer.

2024-09-05 08:00 UTC, jaggarnaut commented on src/views/admin/PersonDetailsView.vue
> +                ></KopersInput>
Habe ich angepasst. Sehr guter Hinweis, danke.

2024-09-05 13:19 UTC, YoussefBouch approved these changes

2024-09-11 13:58 UTC, merged