Spsh 1001
dBildungsplattform/schulportal-client pull request #230
Opened 2024-09-04 10:46 UTC by jaggarnaut

# Description
Use new endpoint /POST createPersonWithPersonenkontexte with a list of Personenkontexte

## Links to Tickets or other PRs
https://ticketsystem.dbildungscloud.de/browse/SPSH-1001
https://github.com/dBildungsplattform/dbildungs-iam-server/pull/640

2024-09-04 10:51 UTC, jaggarnaut commented
we will ignore sonarcloud code coverage because it will be covered in spsh 1021

2024-09-10 17:07 UTC, YoussefBouch requested changes

2024-09-10 17:07 UTC, YoussefBouch commented on src/views/admin/PersonCreationView.vue
> +          rolle.value === personenkontextStore.createdPersonWithKontext?.dBiamPersonenkontextResponses[0]?.rolleId,
Die Kontexte aus der Response mit einem hardcoded Index zu finden finde Ich ein bisschen hacky, was meinst du? 

Sowas würde Ich bevorzugen um Indexes zu vermeiden:

`const schuleKontext= personenkontextStore.createdPersonWithKontext?.dBiamPersonenkontextResponses.find( (context) => context.organisationId === selectedOrganisation.value && context.rolleId === selectedRolle.value ); `

`const klasseKontext= personenkontextStore.createdPersonWithKontext?.dBiamPersonenkontextResponses.find( (context) => context.organisationId === selectedKlasse.value && context.rolleId === selectedRolle.value );`

2024-09-11 07:11 UTC, jaggarnaut commented on src/views/admin/PersonCreationView.vue
> +    }
Aus meiner Sicht hat es keinen Vorteil, weil wir die Variablen so oder so übergeben müssen. In diesem Fall haben wir sogar den Vorteil, dass wir bei der Übergabe ein Objekt nutzen können und die Reihenfolge der Übergabe egal ist.

2024-09-11 07:13 UTC, jaggarnaut commented on src/views/admin/PersonCreationView.vue
> +          rolle.value === personenkontextStore.createdPersonWithKontext?.dBiamPersonenkontextResponses[0]?.rolleId,
Finde ich sinnvoll, wenn wir es als computed umsetzen, die wir überall benutzen können. Gehst du da mit?

2024-09-11 07:26 UTC, YoussefBouch commented on src/views/admin/PersonCreationView.vue
> +          rolle.value === personenkontextStore.createdPersonWithKontext?.dBiamPersonenkontextResponses[0]?.rolleId,
Gehe Ich mit.

2024-09-12 21:06 UTC, YoussefBouch approved these changes

2024-09-13 12:33 UTC, merged