SPSH-1032
dBildungsplattform/schulportal-client pull request #238
Opened 2024-09-10 06:57 UTC by DeFi3298

Frontend Part for implementing KoPersNum Hovering for specific cases. 

[(https://ticketsystem.dbildungscloud.de/browse/SPSH-1032)](https://ticketsystem.dbildungscloud.de/browse/SPSH-1032)

2024-09-10 08:06 UTC, YoussefBouch requested changes

2024-09-10 08:06 UTC, YoussefBouch commented on src/views/ProfileView.vue
> +                            {{ t('missing') }}</span
Doppelpunkt fehlt ;)

2024-09-11 12:26 UTC, DeFi3298 commented on src/views/ProfileView.vue
> +  function checkHasPersMerkmal(): void {
boolean heißt so -> Funktion "hasKoPersMerkmalCheck" genannt

2024-09-11 16:14 UTC, YoussefBouch commented on src/views/ProfileView.vue
> +                            {{ t('missing') }}</span
Fehlt immer noch.

2024-09-12 08:49 UTC, DeFi3298 commented on src/views/ProfileView.vue
> +                            {{ t('missing') }}</span
Hab wohl nicht gepusht... Sollte jetzt da sein.

2024-09-12 10:54 UTC, YoussefBouch commented on src/views/ProfileView.vue
> +                            {{ t('missing') }}</span
![image](https://github.com/user-attachments/assets/ab536dfe-52b7-4f13-a838-aeadf8fd808b)

Schönheit nur aber kann "fehlt" noch mittig sein wie bei den anderen Texten?  und bitte sicherstellen, dass das der gleiche Font class ist?

2024-09-13 08:22 UTC, DeFi3298 commented on src/views/ProfileView.vue
> +                            {{ t('missing') }}</span
Sollte jetzt gut aussehen so wie bei den anderen Feldern!

2024-09-13 17:21 UTC, YoussefBouch commented on src/views/ProfileView.vue
> +                            {{ t('missing') }}</span
Muss leider noch nerven aber es gibt ein extra space zwischen den Doppelpunkten und den Punkt.

KoPers.-Nr. :

2024-09-16 07:08 UTC, DeFi3298 commented on src/views/ProfileView.vue
> +                            {{ t('missing') }}</span
Ist geändert. :)

2024-09-16 07:32 UTC, YoussefBouch approved these changes

2024-09-16 12:40 UTC, merged