Spsh 943
dBildungsplattform/schulportal-client pull request #245
Opened 2024-09-16 13:09 UTC by clauyan

# Description

Display an error message, if the 2FA server is unreachable.

2024-09-18 22:07 UTC, YoussefBouch requested changes

2024-09-18 22:07 UTC, YoussefBouch commented on src/views/ProfileView.vue
> +            </p>
Wenn ein error aus dem Endpunkt get2FA State kommt, soll trotzdem weiter der Profile angezeigt werden? Oder ist es besser ein SPH-alert Komponente zu zeigen wie bei PersonDetailsView z.B.? Hast du das mit Arno geklärt?

2024-09-18 22:07 UTC, YoussefBouch commented on src/views/admin/PersonDetailsView.vue
> +                    </p>
```suggestion
<p v-if="twoFactorAuthentificationStore.serial">
  {{ `${$t('admin.person.twoFactorAuthentication.serial')}: ${twoFactorAuthentificationStore.serial}` }}
</p>

```

2024-09-18 22:07 UTC, YoussefBouch commented on src/views/admin/PersonDetailsView.vue
> +                    </p>
Hier string concatenation vermeiden.

2024-09-18 22:08 UTC, YoussefBouch commented
Playwright Tests müssen hier auch gefixed werden.

2024-09-18 22:10 UTC, YoussefBouch commented on src/views/ProfileView.vue
> +            </p>
NVM! habe gerade das Ticket gelesen :)

2024-09-19 09:02 UTC, clauyan commented on src/locales/de-DE.json
> +          "connection": "Der Server für die Zwei-Faktor-Authentifizierung kann aktuell nicht erreicht werden. Bitte versuchen Sie es zu einem späteren Zeitpunkt erneut."
Ich dachte, dass ich mich an die Scopes halten muss, aber wenn ich den Wert über Scopes hinweg benutzen darf, brauche ich den natürlich nur einmal. Passe ich an.

2024-09-19 10:10 UTC, YoussefBouch commented on src/locales/de-DE.json
> +          "connection": "Der Server für die Zwei-Faktor-Authentifizierung kann aktuell nicht erreicht werden. Bitte versuchen Sie es zu einem späteren Zeitpunkt erneut."
Hast Recht aber hier ist es sowieso im grossen scope "2FA", also das kann gerne auf einmal verkürzt werden ;)

2024-09-27 05:59 UTC, merged