Spsh 1091
dBildungsplattform/schulportal-client pull request #249
Opened 2024-09-19 07:24 UTC by clauyan

# Description

- solves a race condition that would lead to 'Versetzen' not being shown when editing a zuordnung in PersonDetails
- refactored PersonLock so no stores are used and the component is dumb

## Links to Tickets or other PRs

https://ticketsystem.dbildungscloud.de/browse/SPSH-1091

2024-09-23 08:45 UTC, YoussefBouch requested changes

2024-09-23 08:45 UTC, YoussefBouch commented on src/views/admin/PersonDetailsView.vue
> +                  :intersecting-organisations="intersectingOrganisations"
```suggestion
                  :intersectingOrganisations="intersectingOrganisations"
```
Sollte auch gehen und konform sein mit was bisher gemacht wurde.

2024-09-26 09:01 UTC, clauyan commented on src/components/admin/personen/PersonLock.vue
> +        value: v,
Ich habe das geändert und musste dafür noch was im OrganisationStore anpassen. Da gibt es einen Edgde-Case, den ich behandeln musste und deshalb ist da eine Funktion dazu gekommen. Ich versuche nur eine Anfrage ans Backend zu stellen, wenn unbedingt nötig. Kannst du einmal schauen, ob die [Implementation](https://github.com/dBildungsplattform/schulportal-client/pull/249/files#diff-5f829fad2090dc072f3584bd29b5e8e4bb4158ac24ff1685134d87208702d039R254) in Ordnung ist und ob das mit dem Flux-Pattern vereinbar ist?

2024-09-26 13:26 UTC, YoussefBouch requested changes

2024-09-27 08:59 UTC, clauyan commented on src/stores/OrganisationStore.ts
> +        if (!organisation) organisation = this.allOrganisationen.find((org: Organisation) => org.id === organisationId);
Stimmt, aber in der Regel kommt man ja aus dem `PersonManagementView` und da wird der Store gefüllt.

In den meisten Fällen wird der relevante Wert in `parentOrganisationen` sein und wir brauchen den Schritt nicht, aber für den Fall, dass ein Landesadmin die Schulzuordnung eines gesperrten Nutzers entfernt hat, brauchen wir eine Alternative, weil die `parentOrganisationen` dann nicht mehr vorhanden sind. Ich kann auch direkt das Backend fragen, aber ich dachte ich probiere es erst bei `allOrganisations`, um einen Request zu sparen.

2024-10-01 20:40 UTC, YoussefBouch commented
Push geht nicht, vielleicht SRE anschalten?

2024-10-04 12:24 UTC, YoussefBouch approved these changes

2024-10-06 19:21 UTC, YoussefBouch commented on src/views/admin/PersonDetailsView.vue
> +  );
```suggestion
watch(
  () => personStore.currentPerson?.person,
  async (person) => {
    const lockInfo = person?.lockInfo;
    if (person?.isLocked && lockInfo) {
      await organisationStore.getLockingOrganisationById(lockInfo.lock_locked_from);
    }
  }
);
```

Weniger code, gleiches Ergebnis vielleicht?

2024-10-06 19:24 UTC, YoussefBouch commented on src/locales/de-DE.json
> +      "unknownOrganisation": "Unbekannte Organisation"
```suggestion
      "unknownOrganisation": "Unbekannte Organisation."
```

2024-10-06 19:26 UTC, YoussefBouch reviewed
Approved aber Improvable :)

2024-10-07 11:46 UTC, clauyan commented on src/locales/de-DE.json
> +      "unknownOrganisation": "Unbekannte Organisation"
Ergibt meiner Meinung nach keinen Sinn, weil die Organisationsnamen an der Stelle immer ohne Satzzeichen stehen. Es geht um diese Anzeige:

<img width="307" alt="image" src="https://github.com/user-attachments/assets/bb91efa3-16d5-45cb-b2e0-450978fc0e23">

2024-10-07 12:02 UTC, clauyan commented on src/views/admin/PersonDetailsView.vue
> +  );
Ich habe das Destructuring übernommen und die Bedingung zu einer zusammengefasst. Passt das so?

2024-10-08 07:23 UTC, merged