SPSH-1089
dBildungsplattform/schulportal-client pull request #251
Opened 2024-09-20 09:04 UTC by YoussefBouch

# Description

## Links to Tickets or other PRs

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-09-23 15:46 UTC, pkleybolte requested changes

2024-09-23 15:46 UTC, pkleybolte commented on src/stores/RolleStore.ts
> +      rolleServiceProviderQueryParams: RolleServiceProviderQueryParams,
Wäre schöner, wenn die API des Stores von der HTTP-API abstrahiert wäre.

2024-09-23 15:46 UTC, pkleybolte commented on src/views/admin/rollen/RolleCreationView.vue
> +          if (selectedServiceProviders.value && selectedServiceProviders.value.length > 0) {
Es könnte Absicht sein, dass keine ServiceProvider dran hängen, oder?

2024-09-23 22:28 UTC, YoussefBouch commented on src/views/admin/rollen/RolleCreationView.vue
> +          if (selectedServiceProviders.value && selectedServiceProviders.value.length > 0) {
Richtig, deswegen wird `rolleStore.updateServiceProviderInRolle` nicht getriggert, wenn keine SPs ausgewählt wurden.

Der forEach, der vorher da war wurde auch nicht getriggert, wenn der Array selectedServiceProviders empty ist. Foreach ist hier aber nicht nötig, weil wir kein Request pro SP schicken aber wir wollen auch nicht ein Request triggern, wenn nichts bei selectedServiceProviders steht :)

2024-09-23 23:11 UTC, YoussefBouch commented on src/stores/RolleStore.ts
> +      rolleServiceProviderQueryParams: RolleServiceProviderQueryParams,
Done.

2024-09-24 07:08 UTC, pkleybolte approved these changes

2024-09-25 14:02 UTC, closed without merging