Spsh 856
dBildungsplattform/schulportal-client pull request #252
Opened 2024-09-20 13:09 UTC by AlexanderUngefug

2024-09-24 22:47 UTC, YoussefBouch commented
Wenn Ich auf Weiter klicke dann passiert nichts.

![image](https://github.com/user-attachments/assets/feaf7722-5600-47f6-88b0-3f404cbd7e06)

2024-10-01 20:46 UTC, YoussefBouch commented
Ist das jetzt reviewbar?

2024-10-09 22:04 UTC, YoussefBouch commented
Wenn der PR durch ist, kann Ich als QA Tester z.B. nichts mehr testen ohne 2FA Einrichtung, auch wenn Ich mich als Superadmin anmelde. Wie geht man mit sowas um?

2024-10-09 22:51 UTC, YoussefBouch requested changes

2024-10-09 22:51 UTC, YoussefBouch commented on src/views/NoSecondFactor.vue
> +<script setup lang="ts">
Hier bitte die .vue umbennen in NoSecondFactorView

2024-10-09 22:51 UTC, YoussefBouch commented on src/router/routes.ts
> +    name: 'no second factor',
```suggestion
    name: 'no-second-factor',
```

2024-10-09 22:51 UTC, YoussefBouch commented on src/components/alert/SpshAlert.vue
> +        <v-row justify="center">
Bei Small screens sind die Buttons nicht mehr mittig.

2024-10-10 05:33 UTC, AlexanderUngefug commented
> Wenn der PR durch ist, kann Ich als QA Tester z.B. nichts mehr testen ohne 2FA Einrichtung, auch wenn Ich mich als Superadmin anmelde. Wie geht man mit sowas um?

Ich habe dafuer einen eigenen Client in Keycloak angelegt, spsh-no2fa. Dieser umgeht die 2fa Pflicht. Sollte natuerlich in Produktion geloescht werden.

2024-10-10 09:23 UTC, YoussefBouch requested changes

2024-10-10 09:23 UTC, YoussefBouch commented on src/views/NoSecondFactor.spec.ts
> +import { mount, VueWrapper } from '@vue/test-utils';
spec auch umbennen bitte

2024-10-10 09:23 UTC, YoussefBouch commented on src/components/alert/SpshAlert.vue
>    }
Ich würde vielleicht das noch besser einstellen, in dem Ich das ganze in einer neuen Datei in "styles" packe mit dem Namen "alert.scss"

. ::v-depp wird das glaube Ich auch nicht mehr nötig sein, und das bleibt dann konform mit der Art und Weise, wie wir bisher Vuetify Components eingestellt haben.

2024-10-10 13:23 UTC, YoussefBouch approved these changes

2024-10-24 01:01 UTC, merged