Spsh 978
dBildungsplattform/schulportal-client pull request #266
Opened 2024-10-02 14:46 UTC by AlexanderUngefug

2024-10-07 23:46 UTC, YoussefBouch commented on src/views/admin/KlassenManagementView.spec.ts
> +    // expect(wrapper?.findAll('.v-data-table__tr').length).toBe(2); // broken from main branch
Auf main sind bei allen Commits die Tests grün in den letzten 2 Wochen. Bist du hier sicher?

2024-10-08 00:27 UTC, YoussefBouch requested changes

2024-10-08 00:27 UTC, YoussefBouch commented on src/views/ProfileView.vue
>    watchEffect(async () => {
watchEffect ist hier overkill. Wir beobachten nur die person.id und brauchen kein Watcher auf andere Dependencies (Wir haben sowieso keine).

Am besten einfach ein watch nutzen und die Value im Callback kann man dann destrukturieren:

```
watch(
  () => personInfoStore.personInfo?.person.id, 
  async (personId) => {
    if (!personId) return;
    loading2FA.value = true;

    const twoFARequirementPromise: Promise<void> = twoFactorAuthenticationStore.get2FARequirement(personId);
    const personUebersichtPromise: Promise<void> = personStore.getPersonenuebersichtById(personId);
    const twoFAStatePromise: Promise<void> = twoFactorAuthenticationStore.get2FAState(personId);

    await Promise.all([twoFARequirementPromise, personUebersichtPromise, twoFAStatePromise]);
    loading2FA.value = false;
  },
  { immediate: true }
);
```

2024-10-10 08:02 UTC, YoussefBouch approved these changes

2024-10-10 08:03 UTC, YoussefBouch commented on src/views/ProfileView.vue
> +  }
Type geht hier auch?

2024-10-10 08:51 UTC, AlexanderUngefug commented on src/views/ProfileView.vue
> +  }
type geht auch

2024-10-10 13:57 UTC, merged