SPSH-1138
dBildungsplattform/schulportal-client pull request #269
Opened 2024-10-09 08:50 UTC by YoussefBouch

# Description

## Links to Tickets or other PRs

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-10-09 12:47 UTC, jaggarnaut requested changes

2024-10-09 12:47 UTC, jaggarnaut commented on src/views/admin/KlassenManagementView.vue
> +        limit: 25,
Wieso nehmen wir hier nicht das limit aus dem Store? Dann kann der User das Limit nicht mehr selbst festlegen

2024-10-09 12:47 UTC, jaggarnaut commented on src/views/admin/KlassenManagementView.vue
> +      limit: 25,
siehe oben

2024-10-09 12:47 UTC, jaggarnaut commented on src/stores/OrganisationStore.ts
> +        30,
Soll das limit hier auch hardcoded bleiben?

2024-10-09 19:22 UTC, YoussefBouch commented on src/views/admin/KlassenManagementView.vue
> +        limit: 25,
Das ist das Limit für die Orgas im Filter, also hat nichts zu tun mit die Paginierung.

2024-10-09 19:27 UTC, YoussefBouch commented on src/stores/OrganisationStore.ts
> +        30,
Hier hast du aber Recht, das sollte nicht hardcoded sein. Ich nehme es jetzt vom Searchfilterstore! danke.

2024-10-10 11:28 UTC, jaggarnaut approved these changes

2024-10-10 14:37 UTC, merged