SPSH-806
dBildungsplattform/schulportal-client pull request #280
Opened 2024-10-13 19:45 UTC by YoussefBouch

# Description

Email address in the Gesamtübersicht.

## Links to Tickets or other PRs

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-10-15 09:01 UTC, jaggarnaut requested changes

2024-10-15 10:05 UTC, YoussefBouch commented on src/locales/de-DE.json
> +    "emailStatusUnknown": "Unbekannter Status",
Das wird gar nicht angezeigt eigentlich. Das ist in der Logik benutzt um den Default case abzudecken. Ich wollte da einfach kein string schreiben sondern i18 nutzen. Aber Ich passe das trotzdem an, weil das zu den anderen besser passt.

2024-10-16 10:48 UTC, jaggarnaut approved these changes

2024-10-21 11:52 UTC, YoussefBouch commented
mergeable, tests sind auskommentiert wegen SPSH-1021, die werden dann da wieder reinkommen.

2024-10-23 08:11 UTC, merged