Spsh 1111
dBildungsplattform/schulportal-client pull request #286
Opened 2024-10-15 12:47 UTC by he-meyer

# Description

## Links to Tickets or other PRs
https://ticketsystem.dbildungscloud.de/browse/SPSH-1111

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-10-16 13:18 UTC, YoussefBouch requested changes

2024-10-16 13:18 UTC, YoussefBouch commented on src/components/admin/personen/PasswordReset.vue
> +  const printPassword = (): void => {
Ehrlich gesagt bin Ich kein grosser Fan von printWindow und CSS innerhalb <script setup>. Ausserdem nachdem Ich aufs Ticket geguckt habe steht nichts von pdf. Ich würde sagen hier am besten ein Blob erstellen und das Passwort drinne speichern und davon ein downlodable (Text-datei) machen...

Geht sowas gar nicht? 

```
const downloadPassword = (): void => {
  const passwordText: string = props.password;

  // Create a blob from the password text
  const blob = new Blob([passwordText], { type: 'text/plain' });

  const downloadLink = document.createElement('a');
  downloadLink.href = URL.createObjectURL(blob);
  downloadLink.download = `${props.person.person.name.vorname}_password.txt`;

  // Append to the document and trigger download
  document.body.appendChild(downloadLink);

// Here we trigger the download
  downloadLink.click();

  // Clean up the URL object and remove the anchor element
  URL.revokeObjectURL(downloadLink.href);
  document.body.removeChild(downloadLink);
};
```

2024-10-23 10:04 UTC, he-meyer commented
Commit b61768c adds a global variable for the CSP nonce in the test just for testing purposes. The declaration of this global variable in the test needs to be declared with `var` instead of `let` or `const` to avoid a type error when initializing the variable. The eslint no-var rule was deactivated for the specific line when declaring the variable.

2024-10-25 08:44 UTC, YoussefBouch requested changes

2024-10-25 08:44 UTC, YoussefBouch commented on src/components/admin/personen/PasswordReset.vue
> +          <html>
```suggestion
      <!DOCTYPE html>
      <html lang= "de"}">
```

2024-10-25 08:44 UTC, YoussefBouch commented on src/components/admin/personen/PasswordReset.vue
> +  declare var cspNonce: string;
Global declarations wie sowas muss in einer separaten Datei gemacht werden. global.d.ts erstellen neben types.d.ts und bitte da machen. TS hat direkten Zugriff auf solche Variablen und die müssen nicht extra mit "export" deklariert werden.

2024-10-25 09:31 UTC, YoussefBouch approved these changes

2024-10-28 10:52 UTC, merged