SPSH-1192
dBildungsplattform/schulportal-client pull request #288
Opened 2024-10-17 06:49 UTC by he-meyer

# Description

## Links to Tickets or other PRs
https://ticketsystem.dbildungscloud.de/browse/SPSH-1192

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-10-17 07:36 UTC, YoussefBouch approved these changes

2024-10-22 06:40 UTC, jaggarnaut requested changes

2024-10-22 06:40 UTC, jaggarnaut commented on src/styles/components/button.scss
> +      animation: clickAnimation 1s ease forwards;
Wieso wird hier eine Animation verwendet, anstatt die Breite des Buttons anzupassen?

2024-10-24 07:13 UTC, jaggarnaut requested changes

2024-10-24 08:10 UTC, AlexanderUngefug commented on src/styles/components/button.scss
> -      transform: $smallButtonTransformScale;
erledigt

2024-10-24 08:31 UTC, jaggarnaut approved these changes

2024-10-24 09:37 UTC, merged