SPSH-1142
dBildungsplattform/schulportal-client pull request #307
Opened 2024-10-31 14:10 UTC by DeFi3298

Tickets: 
https://ticketsystem.dbildungscloud.de/browse/SPSH-1142
https://ticketsystem.dbildungscloud.de/browse/SPSH-1199
Werden zusammen bearbeitet, da Backend & Frontend

2024-11-07 12:43 UTC, jaggarnaut requested changes

2024-11-07 12:43 UTC, jaggarnaut commented on src/stores/PersonStore.ts
> +  MANUELL_GESPERRT = 'MANUELL_GESPERRT',
Wieso nicht PersonLockOccasion.MANUELL_GESPERRT?

2024-11-07 12:43 UTC, jaggarnaut commented on src/views/admin/PersonDetailsView.spec.ts
> +        lock_occasion: 'MANUELL_GESPERRT',
Wieso nicht PersonLockOccasion.MANUELL_GESPERRT?

2024-11-07 12:43 UTC, jaggarnaut commented on src/stores/PersonStore.ts
> +  MANUELL_GESPERRT = 'MANUELL_GESPERRT',
Bitte überall anpassen, wo sinnvoll

2024-11-07 20:24 UTC, YoussefBouch requested changes

2024-11-08 05:46 UTC, DeFi3298 commented on src/stores/PersonStore.ts
> +  MANUELL_GESPERRT = 'MANUELL_GESPERRT',
done

2024-11-08 05:46 UTC, DeFi3298 commented on src/views/admin/PersonDetailsView.spec.ts
> +        lock_occasion: 'MANUELL_GESPERRT',
done

2024-11-08 05:48 UTC, DeFi3298 commented on src/components/admin/personen/PersonLock.vue
> +      : t('person.unlockError');
Genau, die manuelle Sperrung ist im Frontend quasi äquivalent zum vorherigen isLocked. Diese Sperre entspricht der Sperre durch den Admin und soll unabhängig davon ob ein Benutzer kopers-gesperrt ist oder nicht durchführbar sein.

2024-11-08 09:37 UTC, YoussefBouch commented on src/views/admin/PersonDetailsView.vue
> +            };
Um Wartezeit zu mindern vielleicht übernimmt ihr das? @marode-cap kann leider das heute nicht schaffen. @AlexanderUngefug

2024-11-11 08:32 UTC, DeFi3298 commented on src/views/admin/PersonDetailsView.vue
> +            };
done

2024-11-11 08:45 UTC, YoussefBouch approved these changes

2024-11-11 11:42 UTC, jaggarnaut approved these changes

2024-11-11 11:42 UTC, merged