SPSH-1284
dBildungsplattform/schulportal-client pull request #309
Opened 2024-11-04 14:07 UTC by YoussefBouch

# Description

## Links to Tickets or other PRs

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-11-05 13:04 UTC, jaggarnaut requested changes

2024-11-05 13:04 UTC, jaggarnaut commented on src/components/admin/personen/PersonLock.vue
> +            data-testid="open-lock-dialog-icon"
```suggestion
            data-testid="open-lock-dialog-button"
```

2024-11-05 13:04 UTC, jaggarnaut commented on src/components/admin/personen/PersonLock.vue
> +            data-testid="open-lock-dialog-icon"
Bitte auch beim oberen Button anpassen

2024-11-05 13:51 UTC, YoussefBouch commented on src/components/admin/personen/PersonLock.vue
> +            data-testid="open-lock-dialog-icon"
done

2024-11-06 10:46 UTC, jaggarnaut approved these changes

2024-11-07 10:22 UTC, merged