SPSH-1070
dBildungsplattform/schulportal-client pull request #355
Opened 2024-12-02 08:08 UTC by he-meyer

# Description

## Links to Tickets or other PRs

https://ticketsystem.dbildungscloud.de/browse/SPSH-1070

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-12-03 08:26 UTC, DeFi3298 requested changes

2024-12-03 08:26 UTC, DeFi3298 commented on src/components/admin/personen/PersonLock.vue
> +                    : $t('person.lockUser')
Hardcoded String hier

2024-12-03 08:26 UTC, DeFi3298 commented on src/components/admin/personen/PersonLock.vue
> +                    (lock) => lock.lock_occasion === PersonLockOccasion.MANUELL_GESPERRT,
Wenn isEditMode == false, also gerade nicht editiert wird, steht im Button editLock => dass editiert wird? Hab ich das richtig verstanden und soll das so?

2024-12-03 08:26 UTC, DeFi3298 commented on src/components/admin/personen/PersonLock.vue
> +                }} -->
Kommentar entfernen

2024-12-05 14:04 UTC, DeFi3298 approved these changes

2024-12-10 16:12 UTC, tikle-cap commented on src/components/admin/personen/PersonLock.vue
> +                  !props.person.person.userLock?.some((lock) => lock.lock_occasion === PersonLockOccasion.MANUELL_GESPERRT)
die Bedingung könnte man in eine computed var auslagern

2024-12-10 16:12 UTC, tikle-cap commented on src/components/admin/personen/PersonLock.vue
> +                props.person.person.userLock?.some((lock) => lock.lock_occasion === PersonLockOccasion.MANUELL_GESPERRT) && !isEditMode
bedingung wird oben auch verwendet, daher auch als computed auslagern

2024-12-12 08:51 UTC, tikle-cap approved these changes

2024-12-20 08:37 UTC, YoussefBouch approved these changes

2024-12-20 15:18 UTC, merged