created admin menu bar and added dynamic layout
dBildungsplattform/schulportal-client pull request #48
Opened 2024-01-23 14:29 UTC by jaggarnaut

# Description

## Links to Tickets or other PRs

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-01-29 17:08 UTC, pkleybolte requested changes
Wir haben neulich beschlossen, dass Komponenten 80% Testabdeckung haben sollen. 
Zumindest für die neuen Komponenten sollten wir das einhalten. Besser auch für die editierten.

2024-01-31 14:13 UTC, pkleybolte requested changes

2024-01-31 14:13 UTC, pkleybolte commented on src/views/LandingView.spec.ts
> +  test.skip('it renders the login card', () => {
Warum `skip`?

2024-01-31 14:35 UTC, jaggarnaut commented on src/views/LandingView.spec.ts
> +  test.skip('it renders the login card', () => {
done

2024-01-31 15:50 UTC, pkleybolte approved these changes

2024-02-01 08:00 UTC, merged