WIP: Feature/spsh 60 display service providers
dBildungsplattform/schulportal-client pull request #6
Opened 2023-10-16 14:47 UTC by jaggarnaut

# Description

## Links to Tickets or other PRs

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-10-23 13:08 UTC, marode-cap requested changes

2023-10-24 08:24 UTC, jaggarnaut commented on src/views/auth/LoginView.vue
> +      errorCode.value = error?.response?.data.code
error handling was outsourced to store and a default value was added

2023-10-24 08:25 UTC, jaggarnaut commented on src/stores/ProviderStore.ts
> +        })
store function have been wrapped in try catch blocks with respective error handling

2023-10-24 08:37 UTC, marode-cap approved these changes

2023-10-24 08:39 UTC, merged