Spsh 413 extend person creation form
dBildungsplattform/schulportal-client pull request #90
Opened 2024-02-27 12:39 UTC by jaggarnaut

# Description

## Links to Tickets or other PRs

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-03-04 08:57 UTC, YoussefBouch requested changes

2024-03-04 08:57 UTC, YoussefBouch commented on src/views/admin/PersonCreationView.vue
> +  const schulen: ComputedRef<
Sollten wir das hier nicht eher Organisationen nennen? allOrganisationen[] gibt nicht nur Organisationen vom Typ "Schule" zurück.

2024-03-04 08:57 UTC, YoussefBouch commented on src/views/admin/PersonCreationView.vue
> +    selectedSchule: string;
Sollten wir das hier nicht eher selectedOrganisation nennen? Im Dropdown werden nicht nur Organisationen vom Typ "Schule" angezeigt. Was meinst du?

2024-03-04 08:57 UTC, YoussefBouch commented on src/views/admin/PersonCreationView.vue
> +        :resetForm="resetForm"
:resetForm kann weg, da unbenutzt.

2024-03-04 10:20 UTC, jaggarnaut commented on src/views/admin/PersonCreationView.vue
> +  const schulen: ComputedRef<
Done

2024-03-05 16:49 UTC, pkleybolte approved these changes

2024-03-05 17:21 UTC, YoussefBouch approved these changes

2024-03-07 12:10 UTC, merged