Spsh 411 extend person creation form
dBildungsplattform/schulportal-client pull request #91
Opened 2024-02-29 14:54 UTC by jaggarnaut

# Description

## Links to Tickets or other PRs

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-03-15 09:58 UTC, YoussefBouch requested changes

2024-03-15 09:58 UTC, YoussefBouch commented on src/views/admin/PersonCreationView.vue
> +      buttonClass="primary"
Der Button im Alert ist schon class = primary.

2024-03-15 09:58 UTC, YoussefBouch commented on src/stores/PersonStore.ts
> +    async createPersonenkontext(
Beim nutzen dieses Endpunktes kriege Ich einen Fehler:

```
{
    "message": "Cannot POST /api/dbiam/personenkontext",
    "error": "Not Found",
    "statusCode": 404
}
```

2024-03-15 09:58 UTC, YoussefBouch commented on src/views/admin/PersonCreationView.vue
> +    personStore.createPerson(unpersistedPerson).then(async (personResponse: PersonendatensatzResponse) => {
Hier nutzen wir erstmal den vorherigen Endpunkt, der nur Vorname/Nachname braucht und dann mit der Id dieser Person machen wir einen zweiten Request um den Kontext zu erstellen. 

Das Problem wäre, wenn der zweite Endpunkt einen Fehler wirft, dann wird trotzdem der erste Endpunkt die Person anlegen, nur ohne Kontext... Und in der Ergebnisliste wird die Person ohne Rolle/ Organisationsebene angezeigt und davor auch eine Alert, weil ja personStore.errorCode present ist.

2024-03-15 09:58 UTC, YoussefBouch commented on src/stores/PersonStore.ts
> +const personenKontexteApi: DbiamPersonenkontexteApiInterface = DbiamPersonenkontexteApiFactory(
Ich habe in meinem 443 schon die Stores für Kontexte und Personen separiert, aber vielleicht lassen wir das erstmal so dann bauen wir das später um und wir haben dann auch weniger Konflikte.

2024-03-15 12:19 UTC, jaggarnaut commented on src/views/admin/PersonCreationView.vue
> +      buttonClass="primary"
done

2024-03-15 12:54 UTC, jaggarnaut commented on src/stores/PersonStore.ts
> +    async createPersonenkontext(
Das Deployment war kaputt. Jetzt funktioniert es wieder.

2024-03-15 13:47 UTC, YoussefBouch commented on src/views/admin/PersonCreationView.vue
> +          <v-col class="text-body"> {{ personStore.createdPersonenkontext?.organisationId }}</v-col>
Hier zeigen wir die Ids der Rolle bzw Organisation. War das, was Kristoff optimieren sollte? Um die Rolle und Organisation zu bekommen müssen hier noch 2 Requests abgeschickt werden, nämlich get /personenkontexte/{id} und get /organisationen/{id}

2024-03-15 13:49 UTC, YoussefBouch commented on src/views/admin/PersonCreationView.vue
> +    personStore.createPerson(unpersistedPerson).then(async (personResponse: PersonendatensatzResponse) => {
Würde Ich sagen ja.. um eine Person anzulegen müssen nicht 2 Endpunkte beteiligt sein... Eine Person ohne Kontext macht auch keinen Sinn (Wenn der zweite Requests failed).

2024-03-20 09:44 UTC, YoussefBouch commented on src/views/admin/PersonCreationView.vue
> +          <v-col class="text-body"> {{ personStore.createdPersonenkontext?.organisationId }}</v-col>
Scheinbar auf dem Zettel! Wir lassen das so erstmal dann.

2024-03-21 09:25 UTC, YoussefBouch approved these changes

2024-03-22 10:39 UTC, merged