SPSH-469-Create-404 Page
dBildungsplattform/schulportal-client pull request #95
Opened 2024-03-05 15:20 UTC by casparneumann-cap

# Description
Created A Simple 404 Page for all paths not matching any defined route.

## Links to Tickets or other PRs

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-03-05 16:44 UTC, pkleybolte requested changes

2024-03-05 16:44 UTC, pkleybolte commented on src/views/NotFoundView.vue
> +    <p>Die aufgerufene Seite wurde nicht gefunden</p>
I18n fehlt

2024-03-05 17:17 UTC, YoussefBouch commented on src/views/NotFoundView.vue
> +    <button @click="goBack">Zurück</button>
Ich würde hier gemäss Designvorlage den <v-btn> hinzufügen. Eine einfache Lösung wäre vielleicht den spsh-alert zu nutzen, die wir schon haben dann bleiben wir auch im Design. @pkleybolte was meinst du?

2024-03-06 07:09 UTC, pkleybolte commented on src/views/NotFoundView.vue
> +    <button @click="goBack">Zurück</button>
`spsh-alert` ist eine gut Idee.

2024-03-06 12:09 UTC, YoussefBouch approved these changes

2024-03-07 08:27 UTC, pkleybolte approved these changes

2024-03-07 12:22 UTC, YoussefBouch requested changes

2024-03-07 12:25 UTC, YoussefBouch approved these changes

2024-03-12 11:56 UTC, merged